# Generated by Django 5.0.7 on 2024-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('Running', 'running'), ('Completed', 'completed'), ('cancelled', 'cancelled')], default='Pending', max_length=10),
        ),
    ]
