# Generated by Django 5.0.7 on 2024-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchasemodel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
