# Generated by Django 5.0.7 on 2024-07-15 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_addressmodel_alter_purchasemodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchasemodel'),
        ),
    ]
