# Generated by Django 5.0.7 on 2024-07-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_addressmodel_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='purchase',
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.addressmodel'),
        ),
    ]
