# Generated by Django 5.0.7 on 2024-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_addressmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='user',
        ),
    ]
