# Generated by Django 5.0.7 on 2024-07-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_alter_purchasemodel_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasemodel',
            options={'ordering': ['-date']},
        ),
    ]
