# Generated by Django 5.0.7 on 2024-08-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_alter_purchasemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
